### ISSUE TITLE
No match for 'customize-group RET dropbox'

### ISSUE THREAD

**Issue by NinKenDo64** [pavpanchekha/dropbox.el#3]
After installation, there is no customize-group for dropbox.

GNU Emacs 25.3.1 (x86_64-w64-mingw32)

**Comment by pavpanchekha** [comment]
How did you install the package? Have you made sure the library is loaded? The package may fail to load if the `oauth` or `json` libraries are not available. I am also not sure if the API used by this package is still up and running—I've been meaning to switch over to the new one, but haven't had the time.

**Comment by NinKenDo64** [comment]
Managed to get through this barrier, gonna document it if I ever get this actually working because the way to get through it all is a little Byzantine in terms of how and when you should evaluate things. I've gotten through dropbox-connect at this stage and it seemed okay. What's happening now though is that I do `C+x C+f [RET] /db: [RET]` and it returns `wrong type argument: stringp, nil` Any ideas at this stage? I'd love to getthis working.

**Comment by pavpanchekha** [comment]
I'd love to hear how you got over that first barrier. I'm not sure what is causing the error, but if you set the `debug-on-error` variable to `t` you'll be able to get a traceback, and I might be able to figure something out from that.
