### ISSUE TITLE
Not working; Move to API v2?

### ISSUE THREAD

**Issue by ComedyTomedy** [pavpanchekha/dropbox.el#4]
My specific problems - dropbox-connect throws an error on Dropbox's end, and even once I've entered a token manually, attempting to open file "/db:" throws an error in emacs (Wrong type argument: stringp, nil).

I suspect this is because API v1 finally ended in September 2017.

https://blogs.dropbox.com/developers/2017/06/updated-api-v1-deprecation-timeline/

**Comment by pavpanchekha** [comment]
Yep, known issue, see #2. I would like to do it but am unfortunately short on time recently.
